language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - git clone git://github.com/nikic/scalar_objects.git
  - (cd scalar_objects && phpize && ./configure && make && sudo make install)

before_script:
  - composer install

script:
  - phpunit